name: Go build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
          cache: true

      - name: Build
        run: make build

      - name: Build armel
        run: make package include_packages="linux_armel.tar.gz"

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*
